---
on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Only consider those paths to trigger the action
    paths:
      - 'apps/docs/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm*'
      - '.github/**'
      - 'tsconfig.base.json'

name: 🔍 Continuous integration for docs app

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        node: ['18']
    env:
      TURBO_API: 'http://127.0.0.1:9080'
      TURBO_TEAM: 'next-starter-tpl'
      TURBO_TOKEN: 'local_server_turbo_relaxed_token'

    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: ⚙️ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'

      - name: 🚀 Setup TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ env.TURBO_TOKEN }}

      - name: 📥 Monorepo install
        uses: wayofdev/gh-actions/actions/pnpm-install@master
        with:
          enable-corepack: true
          cache-node-modules: true

      # see https://github.com/vercel/next.js/pull/27362
      - name: ♻️ Restore "docs" app build from cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/docs/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: docs-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: 📝 Typecheck
        working-directory: apps/docs
        run: |
          pnpm lint:types

      - name: 🚨 Linter
        working-directory: apps/docs
        run: |
          pnpm lint

      - name: 🏗 Build docs-app
        working-directory: apps/docs
        run: |
          pnpm --filter=docs build
