---
# https://github.com/google-github-actions/release-please-action#release-types-supported

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - master

name: Release please

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  package-name: next-starter-tpl
                  default-branch: master
                  changelog-types: |
                      [
                        { "type": "feat", "section": "Features", "hidden": false },
                        { "type": "fix", "section": "Bug Fixes", "hidden": false },
                        { "type": "perf", "section": "Performance Improvements", "hidden": false },
                        { "type": "docs", "section": "Documentation", "hidden": false },
                        { "type": "style", "section": "Styles", "hidden": false },
                        { "type": "deps", "section": "Dependencies", "hidden": false },
                        { "type": "refactor", "section": "Code Refactoring", "hidden": false },
                        { "type": "ci", "section": "Continuous Integration", "hidden": false },
                        { "type": "test", "section": "Tests", "hidden": false },
                        { "type": "revert", "section": "Reverts", "hidden": true },
                        { "type": "build", "section": "Build System", "hidden": true },
                        { "type": "chore", "section": "Miscellaneous", "hidden": true }
                      ]
